spring:
    profiles:
        active: local
    datasource:
        url: jdbc:mysql://localhost:3306/stageplan?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
            continue-on-error: true

server:
    port: 8080

jwt:
    secret: ${JWT_SECRET:stageplanSecretKey123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890}
    expiration: 86400000 # 24 hours

mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true
                ssl:
                    trust: smtp.gmail.com

logging:
    level:
        com.jackalone.stageplan: DEBUG
        org.springframework.security: DEBUG
